### ISSUE TITLE
multi-gpu training?

### ISSUE THREAD

**Issue by hengck23** [mitmul/chainer-faster-rcnn#17]
Chainer can support multiple gpus training (in a single machine).
Does this version of faster-rcnn support multi-gpu?

**Comment by mitmul** [comment]
@hengck23 Sorry for late reply. Now it doesn't support multi-GPU training, but it's not so difficult to change the training code to support multi-GPU I think. Well, Hi, we've released the cleaned version of Faster R-CNN inference & **training** codes in ChainerCV: https://github.com/pfnet/chainercv . So, this repository has been actually deprecated. I'll consider to add multi-GPU training codes for Faster R-CNN there, so could you try the [ChainerCV](https://github.com/pfnet/chainercv) repo instead of this code? And please throw an issue when you face a problem :) Thank you!
