### ISSUE TITLE
How much memory is required to run the train.py?

### ISSUE THREAD

**Issue by clockwiser** [mitmul/chainer-faster-rcnn#20]
It seems 32gb cpu memory and 4gb gpu memory is not enough. Is there a hardware requirement for running it?

**Comment by clockwiser** [comment]
Finally got it run. But very slow. It says two days required for 1000 train data and 1000 validation data.

**Comment by mitmul** [comment]
@clockwiser Hi, thank you for trying this code. We've released the cleaned version of Faster R-CNN inference & **training** codes in ChainerCV: https://github.com/pfnet/chainercv . So, this repository has been actually deprecated. Could you try the [ChainerCV](https://github.com/pfnet/chainercv) repo instead of this code? And please throw an issue when you face a problem :) Thank you!
